# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-31 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0002_auto_20210730_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='creted_time',
            new_name='created_time',
        ),
    ]
